"""Durable attachment uploads: optimistic writes and leased background work."""

from datetime import datetime
from typing import Protocol

from smb_requirement_agent.domain.document.attachment import AttachmentUpload


class AttachmentIngestionRepositoryPort(Protocol):
    def add(self, upload: AttachmentUpload) -> None: ...
    def get(self, upload_id: str) -> AttachmentUpload | None: ...
    def save(self, upload: AttachmentUpload, expected_version: int) -> None: ...
    def find_submission(self, actor_id: str, key: str) -> AttachmentUpload | None: ...
    def list_for(self, source_id: str, is_draft: bool) -> tuple[AttachmentUpload, ...]: ...

    def claim(self, now: datetime, until: datetime, token: str) -> AttachmentUpload | None:
        """Lease one queued or expired-lease upload for scanning, or retire it when exhausted."""
        ...

    def pending_finalization(self) -> AttachmentUpload | None:
        """An extracted upload not yet attached to its Requirement or draft."""
        ...
