"""Standalone document persistence, safety and work-claim boundaries."""

from datetime import datetime
from typing import Protocol

from smb_requirement_agent.domain.document.library import LibraryDocument


class DocumentLibraryPort(Protocol):
    def list_attachments(self, source_id: str, is_draft: bool) -> tuple[LibraryDocument, ...]: ...
    def pending_attachment(self) -> LibraryDocument | None: ...
    def has_published(self) -> bool: ...
    def has_incompatible_publication(self, identities: tuple[str, ...]) -> bool: ...
    def lock_publications(self, document_ids: tuple[str, ...]) -> None: ...
    def pending_publication(self, now: datetime) -> LibraryDocument | None: ...
    def add(self, document: LibraryDocument) -> None: ...
    def get(self, document_id: str) -> LibraryDocument | None: ...
    def save(self, document: LibraryDocument, expected_version: int) -> None: ...
    def list_visible(
        self, actor_id: str, offset: int, limit: int
    ) -> tuple[LibraryDocument, ...]: ...
    def find_submission(self, actor_id: str, key: str) -> LibraryDocument | None: ...
    def claim(self, now: datetime, until: datetime, token: str) -> LibraryDocument | None: ...


class DocumentScannerPort(Protocol):
    def scan(self, content: bytes) -> bool:
        """True means clean; False means quarantine; outages must raise, never pass."""
        ...
