"""Metadata persistence boundary for source documents."""

from typing import Protocol

from smb_requirement_agent.domain.document.entities import SourceDocument
from smb_requirement_agent.domain.document.value_objects import DocumentId
from smb_requirement_agent.shared_kernel.identifiers import RequirementId


class DocumentRepositoryPort(Protocol):
    def add(self, document: SourceDocument) -> None: ...
    def get(self, document_id: DocumentId) -> SourceDocument | None: ...
    def save(self, document: SourceDocument) -> None: ...
    def list_all(self) -> list[SourceDocument]: ...
    def list_for_requirement(self, requirement_id: RequirementId) -> list[SourceDocument]: ...
    def list_for_draft(self, draft_id: RequirementId) -> list[SourceDocument]: ...
