import { expect } from "@playwright/test";
import { test } from "./library-fixture";
import path from "node:path";

test("table build waits for owner activation and keeps the old publication available", async ({ page, request }, testInfo) => {
  const narrow = testInfo.project.name === "responsive-chromium";
  if (narrow) await page.setViewportSize({ width: 390, height: 1000 });
  const title = `Table policy ${crypto.randomUUID()}`;
  await page.goto("/documents/library");
  await page.getByLabel("Document title", { exact: true }).fill(title);
  await page.getByLabel("Original file", { exact: true }).setInputFiles({
    name: "policy.csv", mimeType: "text/csv",
    buffer: Buffer.from(`Channel,Rule,Region\nBCRM,"${"Coverage required. ".repeat(50)}",Dubai\nCPP,Private operations,Internal`),
  });
  await page.getByRole("button", { name: "Upload for private review" }).click();
  await expect(page.getByRole("heading", { name: "Review extracted passages" })).toBeVisible({ timeout: 30000 });
  await page.getByRole("checkbox", { name: "Include in shared publication" }).nth(2).uncheck();
  await page.getByLabel("Reason for exclusion").fill("Private operations");
  await page.getByLabel("Review summary").fill("Compared table fields");
  await page.getByRole("button", { name: "Save extraction review" }).click();
  await page.getByRole("button", { name: "Approve saved revision" }).click();
  await expect(page.getByText("Published and searchable", { exact: true })).toBeVisible({ timeout: 30000 });
  const documentId = new URL(page.url()).pathname.split("/").at(-1);
  const apiRoot = `http://127.0.0.1:${process.env.SMOKE_API_PORT ?? "8000"}`;
  const endpoint = `${apiRoot}/library/documents/${documentId}`;
  const previous = await (await request.get(endpoint)).json();
  await page.getByLabel("Replacement file").setInputFiles({ name: "replacement.txt", mimeType: "text/plain", buffer: Buffer.from("Replacement") });
  const reviewedText = page.getByRole("textbox", { name: "Reviewed text", exact: true }).first();
  const savedText = await reviewedText.inputValue();
  await reviewedText.fill(`${savedText} My unsaved correction.`);
  await expect(page.getByRole("button", { name: "Upload new immutable version" })).toBeDisabled();
  await expect(page.getByText("Save your passage changes before uploading a replacement.", { exact: false })).toBeVisible();
  await expect(page.getByRole("button", { name: "Preview table-aware version" })).toBeDisabled();
  await expect(reviewedText).toHaveValue(`${savedText} My unsaved correction.`);
  await page.getByRole("heading", { name: "Upload a replacement" }).locator("..").screenshot({ path: path.resolve("../.impeccable/review", `corpus-dirty-${narrow ? "mobile" : "desktop"}.png`) });
  await reviewedText.fill(savedText);
  await page.getByLabel("Review summary").fill("Saved before building");
  await page.getByRole("button", { name: "Save extraction review" }).click();
  await expect(page.getByRole("button", { name: "Preview table-aware version" })).toBeEnabled();
  await page.getByRole("button", { name: "Preview table-aware version" }).click();
  await expect(page.getByText(/\d+ table-aware chunks/)).toBeVisible();
  await expect(page.getByText("Field label for context: R2C2:").first()).toBeVisible();
  await page.getByRole("button", { name: "Approve and build search version" }).click();
  await expect(page.getByText(/Build ready · \d+ chunks/)).toBeVisible({ timeout: 30000 });
  expect((await (await request.get(endpoint)).json()).published_id).toBe(previous.published_id);
  const activate = page.getByRole("button", { name: "Activate built version" });
  await expect(activate).toBeDisabled();
  const buildSection = page.locator("section").filter({ has: page.getByRole("heading", { name: "Build table-aware search version" }) });
  await expect(buildSection.getByText(/Recorded decisions remain in history/)).toBeVisible();
  await page.evaluate(() => { if (document.activeElement instanceof HTMLElement) document.activeElement.blur(); window.scrollTo(0, 0); });
  await page.screenshot({ path: path.resolve("../.impeccable/review", `corpus-ready-${narrow ? "mobile" : "desktop"}.png`), fullPage: true });
  await buildSection.screenshot({ path: path.resolve("../.impeccable/review", `corpus-controls-${narrow ? "mobile" : "desktop"}.png`) });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("checkbox", { name: "I understand that previous citations will need reconciliation." }).check();
  await activate.click();
  await expect(page.getByText("Published and searchable", { exact: true })).toBeVisible();
  const current = await (await request.get(endpoint)).json();
  expect(current.published_id).not.toBe(previous.published_id);
  await page.getByLabel("Search text", { exact: true }).fill("Coverage");
  await page.getByRole("button", { name: "Search published passages" }).click();
  const results = page.getByRole("region", { name: "Search results" });
  await expect(results.getByRole("link", { name: `${title} · version 1 · Row 2` }).first()).toBeVisible();
  await expect(results.getByText("Private operations", { exact: false })).toHaveCount(0);
  await page.getByRole("button", { name: "Preview table-aware version" }).click();
  await page.getByRole("button", { name: "Approve and build search version" }).click();
  await expect(page.getByText(/Build ready · \d+ chunks/)).toBeVisible({ timeout: 30000 });
  await page.getByRole("button", { name: "Discard pending build" }).click();
  await expect(page.getByText("Previous publication remains searchable", { exact: true })).toBeVisible();
  expect((await (await request.get(endpoint)).json()).published_id).toBe(current.published_id);
});
