import { expect } from "@playwright/test";
import { test } from "./library-fixture";
import { execFileSync } from "node:child_process";
import path from "node:path";

test("slide table rows can be excluded, reviewed and published with exact citations", async ({ page, request }, testInfo) => {
  if (testInfo.project.name === "responsive-chromium") await page.setViewportSize({ width: 390, height: 1000 });
  const root = path.resolve(import.meta.dirname, "../..");
  const python = process.env.SMOKE_PYTHON ?? (process.platform === "win32" ? path.join(root, ".venv/Scripts/python.exe") : "python");
  const buffer = execFileSync(python, ["-c", "import sys; from tests.presentation_fixtures import reviewed_table_presentation; sys.stdout.buffer.write(reviewed_table_presentation())"], { cwd: root });
  const title = `Slide policy ${crypto.randomUUID()}`;
  await page.goto("/documents/library");
  await page.getByLabel("Document title", { exact: true }).fill(title);
  await page.getByLabel("Original file", { exact: true }).setInputFiles({ name: "policy.pptx", mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation", buffer });
  await page.getByRole("button", { name: "Upload for private review" }).click();
  await expect(page.getByRole("heading", { name: "Review extracted passages" })).toBeVisible({ timeout: 30000 });
  await expect(page.getByText(/R\/C labels are positions, not inferred headers/)).toBeVisible();
  const passages = page.getByRole("textbox", { name: "Reviewed text", exact: true });
  await expect(passages).toHaveCount(3);
  await expect(passages.nth(0)).toHaveValue(/Private operations.*spans 2 rows/);
  await expect(passages.nth(1)).toHaveValue(/vertical merge continuation.*R2C2: XGPON التغطية مطلوبة/);
  await page.getByRole("checkbox", { name: "Include in shared publication" }).nth(0).uncheck();
  await page.getByRole("checkbox", { name: "Include in shared publication" }).nth(2).uncheck();
  await page.getByLabel("Reason for exclusion").nth(0).fill("Private anchor row");
  await page.getByLabel("Reason for exclusion").nth(1).fill("Private notes");
  await page.getByLabel("Review summary").fill("Checked original slide table positions and exclusions");
  await page.getByRole("button", { name: "Save extraction review" }).click();
  await page.getByRole("button", { name: "Preview table-aware version" }).click();
  const build = page.locator("section").filter({ has: page.getByRole("heading", { name: "Build table-aware search version" }) });
  await expect(build.getByText("Field label for context: R2C2:").first()).toBeVisible();
  await expect(build.getByText(/Private operations|Private speaker notes/)).toHaveCount(0);
  await build.screenshot({ path: testInfo.outputPath("presentation-preview.png") });
  await page.getByRole("button", { name: "Approve and build search version" }).click();
  await expect(page.getByText(/Build ready · \d+ chunks/)).toBeVisible({ timeout: 30000 });
  await page.getByRole("checkbox", { name: "I understand that previous citations will need reconciliation." }).check();
  await page.getByRole("button", { name: "Activate built version" }).click();
  await expect(page.getByText("Published and searchable", { exact: true })).toBeVisible();
  await page.getByLabel("Search text", { exact: true }).fill("XGPON");
  await page.getByRole("button", { name: "Search published passages" }).click();
  const results = page.getByRole("region", { name: "Search results" });
  const citation = results.getByRole("link", { name: `${title} · version 1 · Slide 1, table 1, row 2` }).first();
  await expect(citation).toBeVisible();
  await expect(results.getByText(/Private operations|Private speaker notes/)).toHaveCount(0);
  const documentId = new URL(page.url()).pathname.split("/").at(-1);
  const apiRoot = `http://127.0.0.1:${process.env.SMOKE_API_PORT ?? "8000"}`;
  const publicResponse = await request.get(`${apiRoot}/library/documents/${documentId}`, { headers: { "X-Fake-Actor-Id": "fake-observer" } });
  expect(publicResponse.ok()).toBe(true);
  const publicDocument = await publicResponse.json();
  expect(publicDocument.versions[0].blocks).toHaveLength(1);
  expect(publicDocument.versions[0].blocks[0].label).toBe("Slide 1, table 1, row 2");
  await page.goto((await citation.getAttribute("href"))!);
  const cited = page.getByRole("region", { name: "Cited published passage" });
  await expect(cited.getByRole("heading", { name: "Slide 1, table 1, row 2" })).toBeVisible();
  await expect(cited.getByText(/Private operations|Private speaker notes/)).toHaveCount(0);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
